name: spa_vehicular
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  url_launcher: ^6.3.0
  socket_io_client: ^2.0.3+1
  http: ^1.2.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.8.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icono.jpg
    - assets/icono_rounded.png
    - assets/branding_v2.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icono.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icono_rounded.png"

flutter_native_splash:
  color: "#013A63"
  image: assets/icono_rounded.png
  branding: assets/branding_v2.png
  branding_mode: bottom
  android_12:
    color: "#013A63"
    image: assets/icono_rounded.png
    icon_background_color: "#013A63"
    branding: assets/branding_v2.png
    branding_mode: bottom