name: spa_vehicular
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  url_launcher: ^6.3.0
  socket_io_client: ^2.0.3+1
  http: ^1.2.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.8.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Comentado para evitar el error de carpeta inexistente.
  # Cuando crees la carpeta assets/animations y tengas archivos adentro, descoméntalo.
  # assets:
  #   - assets/animations/